#!/bin/bash

cmd="./node_modules/there-and-back-again/bin/extract-config-from-markdown"

files=$(cat ./scripts/there-and-back-again-files)

for file in $files
do
  $cmd --config-file $file --markdown-file $file.md
done
